In [4]:
import pandas as pd
import datetime

In [5]:
x=datetime.datetime.today().strftime('%d-%m-%Y') #today date 
file_name_raw = f'luxstay_hanoi_{x}_raw.csv'
df=pd.read_csv(file_name_raw)

In [6]:
df

,Link,Type,Price,Address,Description
0,https://www.luxstay.com//rooms/30837,\n Condominium\n · Vinhomes Met...,$127/night,"Ba Đình, Hà Nội, Vietnam",8 guests · 3 Bedrooms · 2 bathrooms
1,https://www.luxstay.com//rooms/37324,\n Condominium\n · Vinhomes Met...,$79/night $83,"Ba Đình, Hà Nội, Vietnam",4 guests · 2 Bedrooms · 2 bathrooms
2,https://www.luxstay.com//rooms/37438,\n Condominium\n · Vinhomes Met...,$71/night $78,"Ba Đình, Hà Nội, Vietnam",5 guests · 2 Bedrooms · 2 bathrooms
3,https://www.luxstay.com//rooms/29329,\n Condominium\n · Vinhomes Met...,$83/night $87,"Ba Đình, Hà Nội, Vietnam",4 guests · 2 Bedrooms · 2 bathrooms
4,https://www.luxstay.com//rooms/37441,\n Condominium\n,$71/night $79,"Ba Đình, Hà Nội, Vietnam",4 guests · 2 Bedrooms · 2 bathrooms
...,...,...,...,...,...
2674,https://www.luxstay.com//rooms/41465,\n Condominium\n · The Golden ...,$79/night,"Thanh Xuân, Hà Nội, Vietnam",8 guests · 3 Bedrooms · 2 bathrooms
2675,https://www.luxstay.com//rooms/40186,\n Studio Apartment\n,$25/night,"Hoàn Kiếm, Hà Nội, Vietnam",4 guests · 1 Bedroom · 1 bathroom
2676,https://www.luxstay.com//rooms/41978,\n Other\n,$95/night,"Hoàn Kiếm, Hà Nội, Vietnam",8 guests · 3 Bedrooms · 2 bathrooms
2677,https://www.luxstay.com//rooms/40443,\n Entire House\n,$45/night,"Hoàn Kiếm, Hà Nội, Vietnam",10 guests · 3 Bedrooms · 3 bathrooms
2678,https://www.luxstay.com//rooms/40447,\n Entire House\n,$13/night,"Hoàn Kiếm, Hà Nội, Vietnam",2 guests · 1 Bedroom · 1 bathroom

In [7]:
 #get the district from address
df['District'] = df['Address'].apply(lambda x: x.split(',')[0])
    
    #getthe type of building
df['Type']=df['Type'].str.strip() #there are two \n in this field, this removes the first one
df['Type of Home'] = df['Type'].apply(lambda x: x.split('·')[0]) 
df['Type of Home']= df['Type of Home'].str.strip() #remove the last \n left
    
    #geting building name from the dataframe
building_name=[]
for i in range(len(df['Type'])):
    a=df['Type'][i].split('·')
    if len(a) == 2:
        name=a[1] 
    else:
        name='None'
    building_name.append(name)
df['Building Name']= building_name

In [8]:
#Seperate Guest, Bedroom, Bathroom to show the offered numbers but there are still words in it
for n in range(len(df['Description'])):
    y=df['Description'][n].split('·')
    if len(y) != 3:
        df.drop([n],inplace=True)

df['Guest'] = df['Description'].apply(lambda x: x.split('·')[0])
df['Bedroom'] = df['Description'].apply(lambda x: x.split('·')[1])
df['Bathroom'] = df['Description'].apply(lambda x: x.split('·')[2])
#remove the words
df['Guest'] = df['Guest'].apply(lambda x: x.split()[0])
df['Bedroom'] = df['Bedroom'].apply(lambda x: x.split()[0])
df['Bathroom'] = df['Bathroom'].apply(lambda x: x.split()[0])

In [9]:
#get the labelled price
df['Price'] = df['Price'].apply(lambda x: x.split('/')[0])
df['Price'] = df['Price'].str.replace('$','') #remove the dollar sign

In [10]:
#drop unesscessary columns
df.drop(['Description','Address','Type'],axis=1,inplace=True)
    
#format the data type of some columns
df[['Guest','Bedroom','Bathroom']] = df[['Guest','Bedroom','Bathroom']].astype(int)
df['Price'] = df['Price'].astype(float)

In [11]:
df

,Link,Price,District,Type of Home,Building Name,Guest,Bedroom,Bathroom
0,https://www.luxstay.com//rooms/30837,127.0,Ba Đình,Condominium,Vinhomes Metropolis,8,3,2
1,https://www.luxstay.com//rooms/37324,79.0,Ba Đình,Condominium,Vinhomes Metropolis,4,2,2
2,https://www.luxstay.com//rooms/37438,71.0,Ba Đình,Condominium,Vinhomes Metropolis,5,2,2
3,https://www.luxstay.com//rooms/29329,83.0,Ba Đình,Condominium,Vinhomes Metropolis,4,2,2
4,https://www.luxstay.com//rooms/37441,71.0,Ba Đình,Condominium,None,4,2,2
...,...,...,...,...,...,...,...,...
2674,https://www.luxstay.com//rooms/41465,79.0,Thanh Xuân,Condominium,The Golden Palm,8,3,2
2675,https://www.luxstay.com//rooms/40186,25.0,Hoàn Kiếm,Studio Apartment,None,4,1,1
2676,https://www.luxstay.com//rooms/41978,95.0,Hoàn Kiếm,Other,None,8,3,2
2677,https://www.luxstay.com//rooms/40443,45.0,Hoàn Kiếm,Entire House,None,10,3,3
2678,https://www.luxstay.com//rooms/40447,13.0,Hoàn Kiếm,Entire House,None,2,1,1

In [12]:
#store the clean data in csv file
file_name_clean = f'luxstay_hanoi_{x}_clean.csv'
df.to_csv(file_name_clean, index=False, encoding='utf-8')